### ISSUE TITLE
crop_height and crop_width parameters

### ISSUE THREAD

**Issue by amaanda** [feihuzhang/GANet#11]
how do I set these parameters? I tried running `sh predict.sh` on sceneflow dataset and got assertion error, but it works fine with the 1242x375 images from kitti2015 dataset. i thought it was the size of the input image, but the values don't match.

**Comment by feihuzhang** [comment]
The crop size should be multiple of 48.
So you must use 1248x384 as inputs. See “predict.sh”.
Results will be cropped as 1242x375. See “predict.py”.

**Comment by amaanda** [comment]
I understand it now. Thanks!

**Comment by amaanda** [comment]
The height and width must be multiples of 48? Or should the height be multiple of 32?

**Comment by amaanda** [comment]
By stating the crop size should be multiple of 48 you mean the height and the width should both be multiples of 48?

**Comment by feihuzhang** [comment]
Yes, I have stressed this in the readme file.
