### ISSUE TITLE
complie error

### ISSUE THREAD

**Issue by forvd** [feihuzhang/GANet#12]
i reinstall pytorch from source but still got the error like this:
gcc -pthread -B /home/chenly/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/chenly/anaconda3/lib/python3.6/site-packages/torch/include -I/home/chenly/anaconda3/lib/python3.6/site-packages/torch/include/torch/csrc/api/include -I/home/chenly/anaconda3/lib/python3.6/site-packages/torch/include/TH -I/home/chenly/anaconda3/lib/python3.6/site-packages/torch/include/THC -I/usr/local/cuda-9.0/include -I/home/chenly/anaconda3/include/python3.6m -c src/GANet_cuda.cpp -o build/temp.linux-x86_64-3.6/src/GANet_cuda.o -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=GANet -D_GLIBCXX_USE_CXX11_ABI=1 -std=c++11
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
/usr/local/cuda-9.0/bin/nvcc -I/home/chenly/anaconda3/lib/python3.6/site-packages/torch/include -I/home/chenly/anaconda3/lib/python3.6/site-packages/torch/include/torch/csrc/api/include -I/home/chenly/anaconda3/lib/python3.6/site-packages/torch/include/TH -I/home/chenly/anaconda3/lib/python3.6/site-packages/torch/include/THC -I/usr/local/cuda-9.0/include -I/home/chenly/anaconda3/include/python3.6m -c src/GANet_kernel.cu -o build/temp.linux-x86_64-3.6/src/GANet_kernel.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --compiler-options '-fPIC' -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=GANet -D_GLIBCXX_USE_CXX11_ABI=1 -std=c++11
/home/chenly/anaconda3/lib/python3.6/site-packages/torch/include/pybind11/pytypes.h:1205:206: error: expansion pattern ‘pybind11::detail::negation<std::is_same<pybind11::detail::bools<pybind11::detail::negation<std::is_base_of<pybind11::arg, Args> >::value ..., pybind11::detail::negation<std::is_same<pybind11::detail::kwargs_proxy, Args> >::value ..., true>, pybind11::detail::bools<true, pybind11::detail::negation<std::is_base_of<pybind11::arg, Args> >::value ..., pybind11::detail::negation<std::is_same<pybind11::detail::kwargs_proxy, Args> >::value ...> > >::value’ contains no argument packs
/home/chenly/anaconda3/lib/python3.6/site-packages/torch/include/pybind11/pytypes.h:1205:215: error: template argument 1 is invalid
/home/chenly/anaconda3/lib/python3.6/site-packages/torch/include/pybind11/pytypes.h:1205:392: error: expansion pattern ‘pybind11::detail::negation<std::is_same<pybind11::detail::bools<pybind11::detail::negation<std::is_base_of<pybind11::arg, Args> >::value ..., pybind11::detail::negation<std::is_same<pybind11::detail::kwargs_proxy, Args> >::value ..., true>, pybind11::detail::bools<true, pybind11::detail::negation<std::is_base_of<pybind11::arg, Args> >::value ..., pybind11::detail::negation<std::is_same<pybind11::detail::kwargs_proxy, Args> >::value ...> > >::value’ contains no argument packs
/home/chenly/anaconda3/lib/python3.6/site-packages/torch/include/pybind11/pytypes.h:1205:395: error: template argument 2 is invalid
/home/chenly/anaconda3/lib/python3.6/site-packages/torch/include/pybind11/pytypes.h:1205:397: error: template argument 1 is invalid
/home/chenly/anaconda3/lib/python3.6/site-packages/torch/include/pybind11/pytypes.h:1205:397: error: template argument 2 is invalid
/home/chenly/anaconda3/lib/python3.6/site-packages/torch/include/pybind11/pytypes.h:1205:412: error: template argument 1 is invalid
/home/chenly/anaconda3/lib/python3.6/site-packages/torch/include/pybind11/cast.h:776:149: error: expansion pattern ‘std::is_copy_constructible<_Tp>::value’ contains no argument packs
/home/chenly/anaconda3/lib/python3.6/site-packages/torch/include/pybind11/cast.h:776:240: error: expansion pattern ‘std::is_same<typename Container::value_type&, typename Container::reference>::value’ contains no argument packs

**Comment by forvd** [comment]
Any suggestions?

**Comment by ACkuku** [comment]
@forvd maybe you should use cuda-10.0.

**Comment by feihuzhang** [comment]
> @forvd maybe you should use cuda-10.0.
Yes, should change to 9.2 or better 10.0.
That’s a problem for cuda 9.0.

**Comment by Andruola** [comment]
Or u can change **#include "torch/extension.h"** to **#include "torch/types.h"** in libs/GANet/src/*.cu source files. Based on [this](https://discuss.pytorch.org/t/compiling-cpp-cuda-extension-composed-of-multiple-files/30685/3).

**Comment by AutomanHan** [comment]
> Or u can change **#include "torch/extension.h"** to **#include "torch/types.h"** in libs/GANet/src/*.cu source files. Based on [this](https://discuss.pytorch.org/t/compiling-cpp-cuda-extension-composed-of-multiple-files/30685/3).

Maybe .h and .cu need to be replace, .cpp doesn't need.

**Comment by AutomanHan** [comment]
> Or u can change **#include "torch/extension.h"** to **#include "torch/types.h"** in libs/GANet/src/*.cu source files. Based on [this](https://discuss.pytorch.org/t/compiling-cpp-cuda-extension-composed-of-multiple-files/30685/3).

Maybe .h and .cu need to be replace, .cpp doesn't need.
