### ISSUE TITLE
generalization ability on test datasets

### ISSUE THREAD

**Issue by buqing2009** [feihuzhang/GANet#13]
I trained the new model finetuning from kitti2015 on my own datasets, but when i testing, the result disp images are totally wrong because of generalization ability. Imgs in my own datasets are all only one channel(not RGB channel). And when training or testing, i will convert 8bit imgs into 32bit(R/G/B three channels use the same information).  How did this happen?

**Comment by buqing2009** [comment]
I saw the random sort in the original training list file, is that necessary?

**Comment by feihuzhang** [comment]
You should retrain on sceneflow dataset using 8-bit gray image, then fine tune on your own dataset.
Currently, no deep neural network models can generalize well from color input to 8-bit gray images.
