### ISSUE TITLE
Evaluations on KITTI 2015

### ISSUE THREAD

**Issue by alan988chiou** [feihuzhang/GANet#14]
Thank you for your work!
I have already downloaded the [KITTI stereo 2015](http://www.cvlibs.net/download.php?file=data_scene_flow.zip) from the website, but I can not find the ground truth disparity for the testing image, so if I want to test the model and calculate the error on the KITTI test set, how should I do it?
Could you please explain how to evaluate on KITTI test set in more detail?

**Comment by feihuzhang** [comment]
See [Kitti](http://www.cvlibs.net/datasets/kitti/eval_scene_flow.php?benchmark=stereo) about how to submit test results to benchmark for evaluation. 
Benchmarks usually have hidden ground truths for test set.
