### ISSUE TITLE
Can not import GANet after compiling.

### ISSUE THREAD

**Issue by skx6** [feihuzhang/GANet#15]
**I have installed all the environment packages needed:**

gcc==5.4
cuda==10.0.130
python=3.6.3
pytorch==1.0.1

And I have successfully get the ".so" files in "./libs/GANet/build/..." But when I try "python train.py", Another error occurred:

Import error: GANet.cpython-36m-x86_64-linux-gpu.so: undefined symbol: _ZN3c105ErrorC1ENS_14SourceLocationERKSs.

The error comes from ./libs/GANet/functions/GANet.py, the 3rd line: "from ..build.lib import GANet".

Notes: when I build the files, some warnings appeared: 

$ warning: command line option '-Wstrict-prototypes' is valid for C/ObjC but not for C++

$ warning: #warning "Include torch/torch.h for C++ extension is depressed. Please include torch/extension.h"

I guess this is a issue about the difference of **C and C++**, but I have no idea resolve it. Anybody knows?

**Comment by feihuzhang** [comment]
Refer to this https://github.com/feihuzhang/GANet/issues/6

**Comment by skx6** [comment]
@feihuzhang ：Thanks a lot, I have successfully solved this problem by using python3.7 and pytorch1.1.0
