### ISSUE TITLE
some detials about cost volume

### ISSUE THREAD

**Issue by jackkun303** [feihuzhang/GANet#18]
I want to know what's the basic mind to desing the cost volume,why the zero disp is simple copy from the extracted feature of reference img x and query img y,but other disp cost map is copy accroding the width dim? i can not understand this design.
           for i in range(self.maxdisp):
                if i > 0 :
                    cost[:, :x.size()[1], i, :,i:]   = x[:,:,:,i:] (copy data according by the width dim)
                    cost[:, x.size()[1]:, i, :,i:]   = y[:,:,:,:-i]
                else:
                    cost[:, :x.size()[1], i, :,:]   = x
                    cost[:, x.size()[1]:, i, :,:]   = y

**Comment by jackkun303** [comment]
also it means when i >0 cost[:,:x.size()[1], i, :,:i] is zeros ,but why?

**Comment by feihuzhang** [comment]
This is for zero padding.
