### ISSUE TITLE
Load the model without compiling and training

### ISSUE THREAD

**Issue by liuJwei** [feihuzhang/GANet#19]
Thanks for sharing.
Is it possible to use your  pretrained network directly without compiling and training? I see there is no model saved in the .pth file.
Thank you very much.

**Comment by feihuzhang** [comment]
The key layers are implemented with CUDA. Currently, we cannot provide the executable binary files. We can’t get the libraries for your different system environments.
You should compile the cuda code to get the “.so” library for your own system.
Then you can run the prediction/test script after downloading the pretrained models.
