### ISSUE TITLE
Efficiency comparison with PSMNet 

### ISSUE THREAD

**Issue by guduzxc** [feihuzhang/GANet#21]
In your paper, Table 2 shows the Param. comparison results among different cost aggregation methods, and we can see that GANet has fewer param. than that of PSMNet.

However, it seems that GANet needs more GPU mem. that PSMNet during training process. Could tell me the reason for this kind of situation?

Thanks a lot!

**Comment by feihuzhang** [comment]
Please be aware that the number of parameters does **NOT** have any relationship with Mem consumption.
Also, as I told you, the code is the deep model with better results. The paper only reported a simple model. 
I will update the arxiv paper later and release several simple models.
If you want to use PSMNet as a backbone, you can just add the SGA and LGA layers to it. That’s very easy.
