### ISSUE TITLE
Thread self-locking when training parallel.

### ISSUE THREAD

**Issue by skx6** [feihuzhang/GANet#26]
When I try to train the model in parallel, it is locked in the forward process, and warns "require data", I used the default settings but this problems occurred. I guess there is some bug in BN layer designed by user.

**Comment by feihuzhang** [comment]
Sorry, I don’t understand what you mean. I didn’t see such problem.
You should at least change the parameters like the “data_path” when you train your own model. Try to check readme to see which part is not correct.

**Comment by skx6** [comment]
I mean when I use "model=DataParallel(model)" in my training or testing process, the program was stuck in "disp0, disp1, disp2=model(image1, image2)" and seems like an endless loop, but when I delete this line "model=DataParallel(model)" and use only one GPU, the program work normally. 

I also tried other models like resnet in parallel but it works well.

**Comment by skx6** [comment]
Thank you for your response, I have successfully resolved the problem because I activated the annotation "self.disp=torch..." in __init__ function of DisparityRegression and annotate the same line in "forward" function, which caused the cuda device error and self lock occured.
