### ISSUE TITLE
Some problems about loss functions.

### ISSUE THREAD

**Issue by skx6** [feihuzhang/GANet#27]
I plotted the self-defined loss function MyLoss2Function in the forward process in "GANet-master/libs/GANet/functions/GANet.py" in range(0, 10), but find  it discontinious and left the break point of 2 and 3，maybe "temp" is not allowed for assignment inplace because it will still step into the next line instead of jump out.

**Comment by feihuzhang** [comment]
Currently, please do not change the loss settings this is related with an improved loss function and will be talked in a later arxiv paper version. The reviewer asked to add some more analysis, then, there is no space left in the paper to states this.
You can change the loss to l1 or l1smooth loss but should not change the parameters.

**Comment by skx6** [comment]
Thank you for your reply.
