### ISSUE TITLE
Confuse about GetCostVolume

### ISSUE THREAD

**Issue by wujunjie15** [feihuzhang/GANet#28]
Dear, I appreciate your work very much. But i can't understand the following operation: 

            for i in range(self.maxdisp):
                if i > 0 :
                    cost[:, :x.size()[1], i, :,i:]   = x[:,:,:,i:]
                    cost[:, x.size()[1]:, i, :,i:]   = y[:,:,:,:-i]
                else:
                    cost[:, :x.size()[1], i, :,:]   = x
                    cost[:, x.size()[1]:, i, :,:]   = y

where the symbol x and y are respectively the extracted features from the left and right-view? If so, how is it converted into the cost volume? Can you tell me details about the mentioned issues? Thanks again!

**Comment by feihuzhang** [comment]
Yes, x: left view, y: right view. 
CostVolume is built by concatenating x[p] with y[p-i] for all disparity candidates i. (p is the pixels locations at left view).
Zero padding is used when p-i is out of the scope of the right view.

**Comment by passion3394** [comment]
@feihuzhang thanks for your great work. What does the following code mean?
                cost[:, :x.size()[1], i, :,i:]   = x[:,:,:,i:]
                cost[:, x.size()[1]:, i, :,i:]   = y[:,:,:,:-i]
the last index of Variable cost start from i, and assign x's value from i, assign y's value to -i. Why?

**Comment by passion3394** [comment]
why not use the same policy with the else branch?

**Comment by passion3394** [comment]
It seems that I understand! Thanks.
