### ISSUE TITLE
Doubt of pytorch implemet of SGA layers.

### ISSUE THREAD

**Issue by skx6** [feihuzhang/GANet#32]

**Comment by skx6** [comment]
Thank you for your response, I wonder if it is possible to achieve SGA and LGA leayers using pytorch build-in modules only instead of self designed C++?

**Comment by feihu2020** [comment]
Personally, I do not suggest anyone to use the auto gradient in pytorch to realize the SGA layer.

**Comment by skx6** [comment]
@feihu2020 I tried to replace SGA and LGA layers of C++ implement  with pytorch aoto gradient in GANet_deep training, and get a little bit lower performance, but find it time-consuming and memory-costing. A single image need 12G gpu memory and about 10 seconds for one iteration.
