### ISSUE TITLE
How to Import Pretrained Model into Colab Notebook

### ISSUE THREAD

**Issue by derens99** [feihuzhang/GANet#34]
Hello GANet,

I'm currently studying your code and trying to implement it into a colab research python notebook file. How would I go about inserting and running your kitty2015_final pre-trained model? If its not possible on google, how can I get the pre-trained model running on my local machine?

Thanks

**Comment by feihu2020** [comment]
I didn't try the colab, so don't know about details. But, I think that's not difficulty, if you can run other pytorch models.  Only difference is that you need to compile the extension cuda libs before running the prediction script.
