### ISSUE TITLE
Which model used for Middlebury test results

### ISSUE THREAD

**Issue by cp1123** [feihuzhang/GANet#37]
Hi, I see the Middlebury test results on the repo are pretty nice. I wonder what training data you used for the model applied on Middlebury testset. Thanks.

**Comment by feihuzhang** [comment]
I use the pre-trained model on sceneflow dataset "sceneflow_10_epoch.pth" (without finetune on middlebury dataset).
The prediction is run on middlebury dataset (testQ or trainingQ), which has a similar resolution as the sceneflow dataset.

For cityscape, I use "kitti2015_final.pth"

**Comment by cp1123** [comment]
Thank you so much!
