### ISSUE TITLE
Is there 22 3DCNN layers in GANet_deep? I found 23.

### ISSUE THREAD

**Issue by skx6** [feihuzhang/GANet#38]
In GANet paper, GA-Net-N represents for GANet with N 3Dconvolution layers, but I found 23 3D CNN layer in the model.

Here are some blocks in cost aggregation with amount of 3d layers.
1. conv_start:   1
2. sga1:            1
3. conv1a:        1
4. sgal1:           1
5. conv2a:        1
6. deconv2a:    2
7. sgal2:           1
8. deconv1a:    2
9. sga2:            1
10. conv1b       1
11. sgal3:         1
12. conv2b:      1
13. deconv2b:  2
14. sgal4:         1
15. deconv1b:  2
16. sga3:          1
17. disp0:         1
18. disp1:         1
19. disp2:         1
total:                23

Maybe the suffix "N"  didn't take conv_start or disp0/disp1/disp2 into acount? May I know more detail about the evolutionary process of GA-Net-N series? such as the detailed architecture of aggregation in GA-Net-2?

**Comment by feihuzhang** [comment]
It's 22. "3D to 2D" is not counted.
conv1b and conv2b has two 3D conv. 
You can change the hourglass block to encoder-decoder backbone to reduce the number of 3D conv layers.
