### ISSUE TITLE
没有GPU和CUDA进行编译

### ISSUE THREAD

**Issue by fan0210** [feihuzhang/GANet#39]
您好~请问在没有GPU和CUDA的情况下可以编译吗，麻烦您能解答一下，谢谢~

**Comment by feihuzhang** [comment]
The SGA layer is implemented with CUDA. Currently, cpu-only version is not provided. But, you can change the functions in "libs/GANet/functions/GANet.py" and "libs/GANet/src/GANet_kernel.cu" to get a cpu version.
