### ISSUE TITLE
GT range for evaluation

### ISSUE THREAD

**Issue by zzangjinsun** [feihuzhang/GANet#43]
Hello!

From the following implementation, it seems that evaluation results are calculated with truncated ground truth values. Is it same for the reported values in the paper? Thank you very much!

https://github.com/feihuzhang/GANet/blob/c847bb481decfcccbd126274086c0f250109576d/train.py#L150-L159

**Comment by feihuzhang** [comment]
It's set as 192 in all experiments. You can adjust it to 240 or any other if you use your own dataset.

**Comment by zzangjinsun** [comment]
Thank you very much for your reply!
