### ISSUE TITLE
the inference time is much longer than PSMNet

### ISSUE THREAD

**Issue by passion3394** [feihuzhang/GANet#47]
Firstly, thanks for your work! I try to run predict.py on my custom image pair. the accuracy is better than PSMNet. The inference time is about 6 seconds on a 768*1024 Image, but PSMNet only uses 0.8 second for the same image pair.  My GPU is RTX 2080 ti. Could you give me some tips?

**Comment by feihuzhang** [comment]
The deep model is slower than PSMNet. The implementation of cuda functions has too much redundant computations. You can try to re-implement one efficient version (at least for the forward pass).
Or you can simplify the model by 1) reduce the aggregation layers. 2) use one more down-sampling layers in feature extraction.

**Comment by passion3394** [comment]
thanks for your tips. I will try to modify the network.

**Comment by passion3394** [comment]
@feihuzhang BTW, The model kitti2015_final.pth you posted on the google drive is GANet-deep or GANet-15?

**Comment by passion3394** [comment]
@feihuzhang Could you provide your GANet-15 model? thanks very much, I want to test the inference time on my custom dataset

**Comment by feihuzhang** [comment]
> simplify the model by 1) reduce the aggregation layers. 2) use one more down-sampling layers in feature extraction.

Sorry, we are busy with new projects, do not have resources and time to re-train all these models. But, just follow these two rules to revise the "GANet_deep.py" you will get GANet-15 used in the paper, which should be about three times faster than the provided deep model.
Or you can just add some SGA layers to PSMNet to customize the model you want.

**Comment by passion3394** [comment]
@feihuzhang got it. I will try to retrain the model, thx.

**Comment by xy-guo** [comment]
@passion3394 Have you tried GANet11? On my machine, it seems GANet11 is also 2x slower than PSMNet.
