### ISSUE TITLE
how to implement 1-pixel threshold error on Scene Flow dataset? 

### ISSUE THREAD

**Issue by zhiwenfan** [feihuzhang/GANet#51]
Thanks for your generous sharing.
I have one problem with the evaluation mentioned in your paper. You said "GA-Nets are compared with other state-of-the-art DNN models by evaluating with the average end point errors (EPE) and 1-pixel threshold error rates on the test set. "
However, I only find the code for EPE evaluation. Could you please provide how to compute 1-pixel threshold error rates?
Many thanks!

**Comment by feihuzhang** [comment]
Evaluation scripts added.
