### ISSUE TITLE
the training got stuck at the 10th iteration of the first epoch

### ISSUE THREAD

**Issue by passion3394** [feihuzhang/GANet#52]
@feihuzhang I'm try to train the GANet11 model on scene_flow dataset. But the training got stuck at the 10th iteration of the first epoch. Please help to analysis the problem.

system info:
centos7.6
cuda9.2
pytorch1.1.0

the following is the snapshot of the training process:
![1568968259833](https://user-images.githubusercontent.com/14256482/65315432-ad5de780-dbca-11e9-9863-d57e09871872.jpg)

**Comment by passion3394** [comment]
refer to other issues. the author has give a temporary solution:
self.conv_refine1 = BasicConv(8, 8, is_3d=True, kernel_size=1, padding=1)

after adding this layer in GANet11.py. the training goes on.

**Comment by zhiwenfan** [comment]
> refer to other issues. the author has give a temporary solution:
> self.conv_refine1 = BasicConv(8, 8, is_3d=True, kernel_size=1, padding=1)
> 
> after adding this layer in GANet11.py. the training goes on.

hi, seems the syncBN bug only happens with 2080Ti
