### ISSUE TITLE
Could you provide your GANet-15 model? thanks very much

### ISSUE THREAD

**Issue by zhiwenfan** [feihuzhang/GANet#53]
Dear Author, 
Thank you for your sharing.
When searching in your project, I could not find the GANet-15.py.
Could you provide your GANet-15 model? thanks very much

**Comment by haofeixu** [comment]
Hi @zhiwenfan ,
I have tried to replicate GA-Net-15 following Table 6 in the paper, it seems that the  main difference between GA-Net-deep and GA-Net-15 is that GA-Net-15 without `sga11, sga12, sga13, sga14` in [GA-Net-deep definition](https://github.com/feihuzhang/GANet/blob/ca983c77f5211f45da401cde34db40863fa62b5f/models/GANet_deep.py#L308-L311), so I just commented codes related to `sga11, sga12, sga13, sga14`. However, the inference time is much longer (1.5s for 384x1248) than [the results reported by author on KITTI15 benchmark](http://www.cvlibs.net/datasets/kitti/eval_scene_flow_detail.php?benchmark=stereo&result=59cfbc4149e979b63b961f9daa3aa2bae021eff3), I am also wondering is there anything I am missing. Hi @feihuzhang , could you please take a look? thanks!

**Comment by feihuzhang** [comment]
@zhiwenfan The model can be revised from GANet_deep by removing some GA and 3D conv layers (as done by @haofeixu).
@haofeixu The released code is not optimized for speed (to reduce memory usage in backward) with unnecessary computations. We reported the time with our speed-optimized models (>2 times faster). The GPU type may also be different. 
For acceleration, why not try the down-sampling ratio of X4? Only slight influence on accuracy, still far better than PSMNet.

**Comment by haofeixu** [comment]
Hi @feihuzhang , thanks for the reply! Do you mean my implementation of GA-Net-15 is correct, right? 
You mentioned that the model you used is optimized in backward, however, when running inference, only forward is needed, so why optimizing backward leads to faster inference speed? 
BTW, I use V100 to measure the inference time, would you mind sharing your GPU type for inference? Thanks!

**Comment by feihuzhang** [comment]
@haofeixu Yes, one or two 3D conv layers should also be removed for GANet-15. Both forward and backward can be optimized for faster speed. Our released pytorch version has many redundant computations. This is to reduce memory usage.

**Comment by feihuzhang** [comment]
@haofeixu Also change `x = self.LGA2(x, g)`  to `x = self.LGA(x, g)` in DispAgg (line 236).

**Comment by haofeixu** [comment]
Hi @feihuzhang , seems that the difference between `LGA2` and `LGA` is that `LGA2` forwards two times, right? 
I measured the number of parameters and FLOPs of PSMNet and GA-Net-15, GA-Net-15 has more parameters and FLOPs than PSMNet, is this normal? Thanks!

**Comment by feihuzhang** [comment]
No! I don't know how you compare the FLOPs and PSMNet. But, you should use 1) the same feature extraction block. 2) the same down&up-sampling ratio. How did you get that 15 3D conv layers have more parameters than about 30 in PSMNet?

**Comment by haofeixu** [comment]
Currently I directly compare PSMNet with GA-Net-15, the feature extractor of PSMNet has more parameters than GA-Net-15, however, the guidance branch of GA-Net-15 also adds more parameters to learn. The FLOPs is measured by conv layers only, GA-Net-15 with 1/3 cost volume will cause more FLOPs and more parameters (as the disparity dimension increases). Also, the GA layers will result in more FLOPs. Maybe I will try to compare with fixed 1) and 2) as you said. Thanks!

**Comment by feihuzhang** [comment]
In guidance block, just change 3x3 kernel to 1x1 in all reshape layers (e.g. 32 to 640) which cost too many parameters. It doesn't have any influence on accuracy and should not be there. I never pay attentions to this guidance block and only tried compare the cost aggregation and feature extraction blocks.
To compare the number of parameters of the whole model. You should remove all useless layers (defined but not used) and also reduce some unnecessary parameters in reshape layers. 
For FLOPs, you need to fix the down-sampling and up-sampling ratio for GANet, PSMNet and GCNet.
They are all different.

**Comment by haofeixu** [comment]
Hi, @feihuzhang , thanks for the detailed answer! I am also wondering why the GA-Net-deep model costs 1.8s for inference on KITTI benchmark while GA-Net-15 only 0.36s, although they share similar architectures. Are they implemented in a same framework and which type of GPU is used for time counting? Thanks!

**Comment by feihuzhang** [comment]
As I stated, They are based on totally different implementations! Please check the submission time of these two model. GANet-15 implementation consumed 10G mem. The released new implementation of GANet_deep only need 6.5G with even more layers. The faster pytorch version of the GANet-15 runs at about 0.3s/frame on V100 and 0.4s on P40 with 10G mem. The new implementation of GANet-15 is at about 1.0s on V100 and 1.5s on P40with 5.5G mem. Please check the cuda and lib functions for reasons.
We have a caffe version of GANet-2 which runs at >10fps. We also have a new model which achieve better accuracy and faster speed than GANet-deep. We will update it in the arxiv version in the future. We are doing model compression to get real time performance for possible commercial use.

**Comment by zhiwenfan** [comment]
> As I stated, They are based on totally different implementations! Please check the submission time of these two model. GANet-15 implementation consumed 10G mem. The released new implementation of GANet_deep only need 6.5G with even more layers. The faster pytorch version of the GANet-15 runs at about 0.3s/frame on V100 and 0.4s on P40 with 10G mem. The new implementation of GANet-15 is at about 1.0s on V100 and 1.5s on P40with 5.5G mem. Please check the cuda and lib functions for reasons.
> We have a caffe version of GANet-2 which runs at >10fps. We also have a new model which achieve better accuracy and faster speed than GANet-deep. We will update it in the arxiv version in the future. We are doing model compression to get real time performance for possible commercial use.

Thank you for your kind help

**Comment by haofeixu** [comment]
Hi @feihuzhang , I further measured the FLOPs of the cost aggregation modules in PSMNet and GA-Net with [an open source tool](https://github.com/Lyken17/pytorch-OpCounter). They are both compared with same downsampling ratio (1/4). However, I found that the [cost aggreagtion module in GA-Net](https://github.com/feihuzhang/GANet/blob/ca983c77f5211f45da401cde34db40863fa62b5f/models/GANet_deep.py#L285-L302) has more FLOPs than [PSMNet](https://github.com/JiaRenChang/PSMNet/blob/92614984ae582740aabd8a4dee9e60aa9e4c821f/models/stackhourglass.py#L59-L82), even without including the GA layers. I think the reason is that GA-Net uses higher resolution feature maps, while PSMNet uses downsampling layers more frequently. When considering the guidance branch and the GA layers, more FLOPs will be introduced. The LGA layer also costs more FLOPs, as it is used in the original resolution.
