### ISSUE TITLE
something wrong in GANet_kernel.cu

### ISSUE THREAD

**Issue by jiahaoruan** [feihuzhang/GANet#59]
thank you for your code very much.it means to me a lot.
however, i find something which makes me confused.
for example,there is something wrong in the computation of backpropagation for the row=0 in __global__void sga_down_data_backward().it shoud be something like that,x*(w0+w1+w2+w3+w4) instead of  x*(w0).
i wanna know is it somthing you made for some reasons or i miss something important?

**Comment by feihuzhang** [comment]
This is for consistence with the forward function.
In the border, it uses the "replicate" padding.
Can remove this if "zero padding" are used in the forward function.

**Comment by jiahaoruan** [comment]
do you mind if you write in chinese?
仍然是刚刚那个函数，我注意到你在d为0的时候，你是x*（w0+w2）的形式，d=depth时，你是x*（w0+w3）。也就是说你的‘replicate ’padding是参与反向传播的，但是你在row=0时却不是x*（w0+w1+w2+w3）。因为我注意到你在forward是对边缘全是‘replicate ’padding。
