### ISSUE TITLE
undefined symbol :    when import GANet from libs

### ISSUE THREAD

**Issue by buqing2009** [feihuzhang/GANet#6]
Here is the error code:

```
Traceback (most recent call last):
  File "train.py", line 5, in <module>
    from libs.GANet.modules.GANet import MyLoss2
  File "/data/bq/GANet-master/libs/GANet/modules/__init__.py", line 1, in <module>
    from .GANet import *
  File "/data/bq/GANet-master/libs/GANet/modules/GANet.py", line 5, in <module>
    from ..functions import *
  File "/data/bq/GANet-master/libs/GANet/functions/__init__.py", line 1, in <module>
    from .GANet import *
  File "/data/bq/GANet-master/libs/GANet/functions/GANet.py", line 3, in <module>
    from ..build.lib import GANet
ImportError: /data/bq/GANet-master/libs/GANet/build/lib/GANet.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN3c105ErrorC1ENS_14SourceLocationERKSs
```

**Comment by feihuzhang** [comment]
It might be a lib conflicts.
Please see whether this helps.
https://github.com/SeanNaren/warp-ctc/issues/103

Rebuilding the pytorch from the source would avoid most of the library problems.
Also make sure you are using all the same libraries when you compile the extension libs.

**Comment by buqing2009** [comment]
> It might be a lib conflicts.
> Please see whether this helps.
> [SeanNaren/warp-ctc#103](https://github.com/SeanNaren/warp-ctc/issues/103)
> 
> Rebuilding the pytorch from the source would avoid most of the library problems.
> Also make sure you are using all the same libraries when you compile the extension libs.

The pytorch was built from the source, the version of pytorch is 1.0.0, the env is Ubuntu16.04 , CUDA9.2, python3.6.

**Comment by buqing2009** [comment]
It can solve the above conflicts, thanks. But i found anther problem, I will close it, and open the new one.

**Comment by aasharma90** [comment]
Not really sure if it is the correct solution, but when I compiled the libraries with `gcc=5.5, python=3.7, pytorch=1.1.0, ubuntu=18.04, cuda=10.0`, I could get past the "undefined symbol" error.
