### ISSUE TITLE
question in GANet_kernel.cu

### ISSUE THREAD

**Issue by jiahaoruan** [feihuzhang/GANet#60]
作者你好，我注意到你的forward用的是replicate padding。你在backward的时候，你在d=0时，是x*（w0+w2）的形式，d=depth时，是x*（w0+w3）的形式，也就是说你的边缘是参与到反向传播的，但是你的row=0时却不是x*（w0+w1+w2+w3+w4）的情况，而是x*（w0）。

**Comment by feihuzhang** [comment]
这个是和padding有关……有些注释掉的代码是在做backward的padding……有些不一致train的时候发现稍微好一丢丢……但影响不大基本可以忽略……backward时候做不做边缘的padding影响不是很大……但forward时候不能用zero padding否则边缘会被变小。

**Comment by jiahaoruan** [comment]
实在太感谢了！！！！！！
