### ISSUE TITLE
Training on my own data

### ISSUE THREAD

**Issue by YJonmo** [feihuzhang/GANet#65]
Where are the trained weigh saved? I trained the network and can see the loss droping but I don't see any trained wait. I used these arguments (only yhe log file was saved):

CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 

python train.py --batchSize=1 \
                --crop_height=384 \
                --crop_width=384 \
                --max_disp=192 \
                --thread=16 \
                --data_path='/home/jonmoham/DataForTraining/BlenderData/' \
                --training_list='lists/blender_train.list' \
                --save_path='/home/jonmoham/Python/GANet/Output_Blender2' \
                --resume='' \
                --model='GANet_deep' \
                --nEpochs=11 2>&1 |tee logs/log_train_Blender2.txt

By the way, was an error when the first time I want to train the model on my own data:

Traceback (most recent call last):
  File "train.py", line 5, in <module>
    from libs.GANet.modules.GANet import MyLoss2
  File "/.../Python/GANet/libs/GANet/modules/__init__.py", line 1, in <module>
    from .GANet import *
  File "/.../Python/GANet/libs/GANet/modules/GANet.py", line 140
    self.maxdisp = maxdisp + 1
TabError: inconsistent use of tabs and spaces in indentation

So I had to manually correct the indentation.

**Comment by feihuzhang** [comment]
It's a "tab" "space" issue. Just change "tab" to four "space" before this line.
self.maxdisp = maxdisp + 1
