### ISSUE TITLE
Number of parameters 

### ISSUE THREAD

**Issue by waychin-weiqin** [feihuzhang/GANet#66]
Hi author, 

Just wondering how did you calculate or get the information about the number of parameters from your work and also from PSMNet? 

I am aware that in PSMNet's code, they did provide a line that will output the total number of parameters in their network. However, that number if different from the one you had in your paper. So I am wondering if you used different method to extract the number of parameters. 

Thank you.

**Comment by feihuzhang** [comment]
The paper only reported the Parameters for cost aggregation. It fixed the feature extraction network.
For the guidance network, you can try to change all the following rehsape convolutional layers to 1x1. It's my mistakes to use a 3x3 kernels. It should be 1x1.
        self.weight_sg1 = nn.Conv2d(32, 640, (3, 3), (1, 1), (1, 1), bias=False)
        self.weight_sg2 = nn.Conv2d(32, 640, (3, 3), (1, 1), (1, 1), bias=False)
        self.weight_sg3 = nn.Conv2d(32, 640, (3, 3), (1, 1), (1, 1), bias=False)

        self.weight_sg11 = nn.Conv2d(48, 960, (3, 3), (1, 1), (1, 1), bias=False)
        self.weight_sg12 = nn.Conv2d(48, 960, (3, 3), (1, 1), (1, 1), bias=False)
        self.weight_sg13 = nn.Conv2d(48, 960, (3, 3), (1, 1), (1, 1), bias=False)
        self.weight_sg14 = nn.Conv2d(48, 960, (3, 3), (1, 1), (1, 1), bias=False)
