### ISSUE TITLE
Grayscale image results from kitti2015 - miss colors

### ISSUE THREAD

**Issue by TBdt38** [feihuzhang/GANet#67]
Hi,

thanks for the very good work!
i have a strange behavior when i try to predict images with your network. I get as results grayscale images instead of colored!
is there any option to modify to get color depth image?
for instance see the image below, result of kitti2015  000000_10.png processing.
![bug_grayscale](https://user-images.githubusercontent.com/34160721/69431734-9ce7fb80-0d38-11ea-95dd-843f28b6c8dd.png)

Any idea why this is happening? i have the same thing with the 3 models.
thanks in advance

**Comment by feihuzhang** [comment]
Are you talking about visualization or color coding of the disparity map?
You should refer to KITTI development tools.

**Comment by TBdt38** [comment]
the output of the network gives a grayscale dispartity map like the screenshot above.
