### ISSUE TITLE
关于SGA模块中的第五项

### ISSUE THREAD

**Issue by seeyouagain111** [feihuzhang/GANet#68]

**Comment by seeyouagain111** [comment]
大佬你好，论文里的公式讲到第五项为max（C(p-r),i）意思是取与相邻像素d间隔大于1的中C(p-r)的最大值，可是我在源码里找到第五项的公式top_data[base0-width+k*step]*filters[shift+4*step]     我的理解是求p-r方向的视差为d+k。请问这和max的定义是怎么联系起来的，望回复

**Comment by feihuzhang** [comment]
求 的是 p-r 方向上任意一个 candidate i=0... D_max的maximum。 k 是 maximum的index。

**Comment by ljp1997** [comment]
> 求 的是 p-r 方向上任意一个 candidate i=0... D_max的maximum。 k 是 maximum的index。

请问关于max C((p-r),i), 论文里提到C的维度是（H，W，D，F），C((p-r),i)索引出来的元素是一个长度为F的向量吗，如果是向量的话怎么比较向量的大小呢
