### ISSUE TITLE
AssertionError when training

### ISSUE THREAD

**Issue by buqing2009** [feihuzhang/GANet#7]
When i was finetuning the model, it would assert in the forward stage , here is the Traceback code:
```
Traceback (most recent call last):
  File "train.py", line 185, in <module>
    train(epoch)
  File "train.py", line 106, in train
    disp0, disp1, disp2=model(input1,input2)
  File "/usr/local/miniconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/miniconda3/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 141, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/usr/local/miniconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/data/bq/GANet-master/models/GANet_deep.py", line 386, in forward
    x = self.feature(x)
  File "/usr/local/miniconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/data/bq/GANet-master/models/GANet_deep.py", line 113, in forward
    x = self.deconv4a(x, rem3)
  File "/usr/local/miniconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/data/bq/GANet-master/models/GANet_deep.py", line 65, in forward
    assert(x.size() == rem.size())
AssertionError
```

**Comment by feihuzhang** [comment]
Try to set the crop width and height as multiple of 48.
If doesn't work, print and show me the x.size() and rem.size().

**Comment by buqing2009** [comment]
> Try to set the crop width and height as multiple of 48.
> If doesn't work, print and show me the x.size() and rem.size().

Yes, i set the wrong crop size. Its OK now, another question: what the relation between bacthSize/thread and GPU memory?

**Comment by skumailraza** [comment]
> Try to set the crop width and height as multiple of 48.
> If doesn't work, print and show me the x.size() and rem.size().

ASSERT torch.Size([4, 96, 10, 10])==torch.Size([4, 96, 10, 10])?
ASSERT torch.Size([4, 64, 20, 20])==torch.Size([4, 64, 20, 20])?
ASSERT torch.Size([4, 48, 40, 40])==torch.Size([4, 48, 40, 40])?
ASSERT torch.Size([4, 32, 80, 80])==torch.Size([4, 32, 80, 80])?
ASSERT torch.Size([4, 48, 40, 40])==torch.Size([4, 48, 40, 40])?
ASSERT torch.Size([4, 64, 20, 20])==torch.Size([4, 64, 20, 20])?
ASSERT torch.Size([4, 96, 10, 10])==torch.Size([4, 96, 10, 10])?
ASSERT torch.Size([4, 128, 5, 5])==torch.Size([4, 128, 5, 5])?
ASSERT torch.Size([4, 96, 10, 10])==torch.Size([4, 96, 10, 10])?
ASSERT torch.Size([4, 64, 20, 20])==torch.Size([4, 64, 20, 20])?
ASSERT torch.Size([4, 48, 40, 40])==torch.Size([4, 48, 40, 40])?
ASSERT torch.Size([4, 32, 80, 80])==torch.Size([4, 32, 80, 80])?
ASSERT torch.Size([4, 96, 10, 10])==torch.Size([4, 96, 10, 10])?
ASSERT torch.Size([4, 64, 20, 20])==torch.Size([4, 64, 20, 20])?
ASSERT torch.Size([4, 48, 40, 40])==torch.Size([4, 48, 40, 40])?
ASSERT torch.Size([4, 32, 80, 80])==torch.Size([4, 32, 80, 80])?
ASSERT torch.Size([4, 48, 40, 40])==torch.Size([4, 48, 40, 40])?
ASSERT torch.Size([4, 64, 20, 20])==torch.Size([4, 64, 20, 20])?
ASSERT torch.Size([4, 96, 10, 10])==torch.Size([4, 96, 10, 10])?
ASSERT torch.Size([4, 128, 5, 5])==torch.Size([4, 128, 5, 5])?
ASSERT torch.Size([4, 96, 10, 10])==torch.Size([4, 96, 10, 10])?
ASSERT torch.Size([4, 64, 20, 20])==torch.Size([4, 64, 20, 20])?
ASSERT torch.Size([4, 48, 40, 40])==torch.Size([4, 48, 40, 40])?
ASSERT torch.Size([4, 32, 80, 80])==torch.Size([4, 32, 80, 80])?
ASSERT torch.Size([4, 48, 33, 40, 40])==torch.Size([4, 48, 33, 40, 40])?
**ASSERT torch.Size([4, 32, 65, 80, 80])==torch.Size([4, 32, 66, 80, 80])?**
Assert fails here! Crop width and height are 240 and 144 respectively.
