### ISSUE TITLE
Why can I get a disparity map in the range of 0 ~ 255 through kitti2015_final.pth?

### ISSUE THREAD

**Issue by USTC-Keyanjie** [feihuzhang/GANet#71]
Thank you for this great job!

When I read the code, I found that you scaled the GT to between 0 and 1.  Then, when inference, a disparity map between 0 and 1 should also be output.

However, what I get through `kitti2015_final.pth` is a disparity map of 0 ~ 255. Do you know why this is?

**Comment by feihuzhang** [comment]
Please check the readme file of KITTI benchmark.
The results and the ground truths are all stored as 16bit images.
