### ISSUE TITLE
Compilation issues

### ISSUE THREAD

**Issue by binwang777** [feihuzhang/GANet#73]
Must GCC version be 5.4.0？
After compiling with gcc5.5, there is no GANet under GANet-master / libs / GANet / build / lib.
from ..build.lib import GANet                 is wrong

**Comment by feihuzhang** [comment]
gcc >= 5.3 are all applicable. gcc5.5 has already been tested.
It must be some complication error of pytorch.
Could you provide the error message when you compiling the library?

**Comment by binwang777** [comment]
src/gpu/sync_bn_cuda.cu: In lambda function:
src/gpu/sync_bn_cuda.cu:339:124: warning: ‘c10::ScalarType detail::scalar_type(const at::DeprecatedTypeProperties&)’ is deprecated [-Wdeprecated-declarations]
/home/ubuntu/anaconda3/lib/python3.7/site-packages/torch/include/ATen/Dispatch.h:47:1: note: declared here
 inline at::ScalarType scalar_type(const at::DeprecatedTypeProperties &t) {
 ^
src/gpu/sync_bn_cuda.cu: In lambda function:
src/gpu/sync_bn_cuda.cu:382:122: warning: ‘c10::ScalarType detail::scalar_type(const at::DeprecatedTypeProperties&)’ is deprecated [-Wdeprecated-declarations]
/home/ubuntu/anaconda3/lib/python3.7/site-packages/torch/include/ATen/Dispatch.h:47:1: note: declared here
 inline at::ScalarType scalar_type(const at::DeprecatedTypeProperties &t) {
 ^
src/gpu/sync_bn_cuda.cu: In lambda function:
src/gpu/sync_bn_cuda.cu:414:122: warning: ‘c10::ScalarType detail::scalar_type(const at::DeprecatedTypeProperties&)’ is deprecated [-Wdeprecated-declarations]
/home/ubuntu/anaconda3/lib/python3.7/site-packages/torch/include/ATen/Dispatch.h:47:1: note: declared here
 inline at::ScalarType scalar_type(const at::DeprecatedTypeProperties &t) {
 ^
src/gpu/sync_bn_cuda.cu: In lambda function:
src/gpu/sync_bn_cuda.cu:438:122: warning: ‘c10::ScalarType detail::scalar_type(const at::DeprecatedTypeProperties&)’ is deprecated [-Wdeprecated-declarations]
/home/ubuntu/anaconda3/lib/python3.7/site-packages/torch/include/ATen/Dispatch.h:47:1: note: declared here
 inline at::ScalarType scalar_type(const at::DeprecatedTypeProperties &t) {
 ^
src/gpu/sync_bn_cuda.cu: In lambda function:
src/gpu/sync_bn_cuda.cu:470:124: warning: ‘c10::ScalarType detail::scalar_type(const at::DeprecatedTypeProperties&)’ is deprecated [-Wdeprecated-declarations]
/home/ubuntu/anaconda3/lib/python3.7/site-packages/torch/include/ATen/Dispatch.h:47:1: note: declared here
 inline at::ScalarType scalar_type(const at::DeprecatedTypeProperties &t) {
 ^
g++ -pthread -shared -B /home/ubuntu/anaconda3/compiler_compat -L/home/ubuntu/anaconda3/lib -Wl,-rpath=/home/ubuntu/anaconda3/lib -Wl,--no-as-needed -Wl,--sysroot=/ build/temp.linux-x86_64-3.7/src/gpu/operator.o build/temp.linux-x86_64-3.7/src/gpu/sync_bn_cuda.o -L/usr/local/cuda-10.0/lib64 -lcudart -o build/lib.linux-x86_64-3.7/sync_bn_gpu.cpython-37m-x86_64-linux-gnu.so


As above, there are some caveats, but training and evaluation are now normal. This is the result of my evaluation on kitti2015, I don't know if it is accurate.

===> Total 200 Frames ==> AVG EPE Error: 0.3550, AVG Error Rate: 0.0053
