### ISSUE TITLE
disp2 in ganet_deep is  all zeros

### ISSUE THREAD

**Issue by chenglong0313** [feihuzhang/GANet#76]
my environment is pytorch 1.1  and cuda 10.0 .
In compiling, there is no error occuring.
But when running ganet_deep.py , sync bn is wrong. Then i replace sync BN by pytorch common BN.
At last, everything looks ok.  but when training on sceneflow ,  disp0 and disp1 looks just ok, but disp2 output is all zeros.

so i want to ask:
(1)what effect  will  occur  in  replacing sync BN by pytorch common BN ,  just lower  the performance?
（2）Why is this happening ?  Is it a compilation error?

**Comment by feihuzhang** [comment]
It's not the problem of bn or sync BN. It's possibly the compling error of LGA code.
Try to check the output of the LGA layer.
If you has trouble with the provided sync bn try to use the NVIDIA apex syncbn (see the updated readme)
