### ISSUE TITLE
how to delete":" in compile.sh

### ISSUE THREAD

**Issue by Lvhhhh** [feihuzhang/GANet#8]
thank you for your work, when i sh compile.sh 
it occurs error: 
unable to execute '/usr/local/cuda-10.1:/bin/nvcc': No such file or directory
error: command '/usr/local/cuda-10.1:/bin/nvcc' failed with exit status 1

how to delete ":" in this path.
thank you for your time

**Comment by Lvhhhh** [comment]
the pytorch is 1.1 ubuntu16.04 and python3.6 cuda10.1
i test in pytoch 1.0 ubuntu16.04 python3.5 cuda8.0 has the same error
how to delete the ":"??thaks

**Comment by feihuzhang** [comment]
It should be an issue of your environment $PATH.
you should be able to check by “echo $PATH”.
In “compile.sh” there is example to set temporary PATH , CUDA_HOME and LD_LIBRARY_PATH.

**Comment by Lvhhhh** [comment]
> It should be an issue of your environment $PATH.
> you should be able to check by “echo $PATH”.
> In “compile.sh” there is example to set temporary PATH , CUDA_HOME and LD_LIBRARY_PATH.

thank you for your answer,but i have occurred another problem.
here is the error:
/usr/bin/python3.6m /usr/lib/pycharm-community/helpers/pydev/pydevd.py --multiproc --qt-support --client 127.0.0.1 --port 36827 --file /home/lvhao/GANet-master/train.py --batchSize=4 --crop_height=240 --crop_width=528 --thread=4 --data_path=/home/lvhao/data/kitti_stereo_2015/training/ --training_list=/home/lvhao/GANet-master/lists/kitti2015_train.list --save_path='./checkpoint/finetune_kitti2015' --kitti2015=1 --shift=3 --resume='./checkpoint/sceneflow_epoch_10.pth' --nEpochs=800
warning: Debugger speedups using cython not found. Run '"/usr/bin/python3.6m" "/usr/lib/pycharm-community/helpers/pydev/setup_cython.py" build_ext --inplace' to build.
pydev debugger: process 26233 is connecting

Connected to pydev debugger (build 163.8233.8)
Namespace(batchSize=4, crop_height=240, crop_width=528, cuda=1, data_path='/home/lvhao/data/kitti_stereo_2015/training/', kitti=0, kitti2015=1, left_right=0, lr=0.001, max_disp=192, nEpochs=800, resume="'./checkpoint/sceneflow_epoch_10.pth'", save_path="'./checkpoint/finetune_kitti2015'", seed=123, shift=3, testBatchSize=1, threads=4, training_list='/home/lvhao/GANet-master/lists/kitti2015_train.list', val_list='./lists/sceneflow_test_select.list')
===> Loading datasets
===> Building model
=> no checkpoint found at ''./checkpoint/sceneflow_epoch_10.pth''
0.001
Traceback (most recent call last):
  File "/usr/lib/pycharm-community/helpers/pydev/pydevd.py", line 1596, in <module>
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/usr/lib/pycharm-community/helpers/pydev/pydevd.py", line 974, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/usr/lib/pycharm-community/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/lvhao/GANet-master/train.py", line 184, in <module>
    train(epoch)
  File "/home/lvhao/GANet-master/train.py", line 105, in train
    disp0, disp1, disp2=model(input1,input2)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/parallel/data_parallel.py", line 150, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/lvhao/GANet-master/models/GANet_deep.py", line 385, in forward
    g = self.conv_start(x)	
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/container.py", line 92, in forward
    input = module(input)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/lvhao/GANet-master/models/GANet_deep.py", line 38, in forward
    x = self.bn(x)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/lvhao/GANet-master/libs/sync_bn/modules/sync_bn.py", line 121, in forward
    self.activation, self.slope).view(input_shape)
  File "/home/lvhao/GANet-master/libs/sync_bn/functions/sync_bn.py", line 58, in forward
    _ex, _exs = sync_bn_gpu.expectation_forward(x)
RuntimeError: cudaGetLastError() == cudaSuccess ASSERT FAILED at src/gpu/sync_bn_cuda.cu:424, please report a bug to PyTorch. (Expectation_Forward_CUDA at src/gpu/sync_bn_cuda.cu:424)
frame #0: std::function<std::string ()>::operator()() const + 0x11 (0x7f869c60e441 in /usr/local/lib/python3.6/dist-packages/torch/lib/libc10.so)
frame #1: c10::Error::Error(c10::SourceLocation, std::string const&) + 0x2a (0x7f869c60dd7a in /usr/local/lib/python3.6/dist-packages/torch/lib/libc10.so)
frame #2: Expectation_Forward_CUDA(at::Tensor) + 0x281 (0x7f869928d394 in /home/lvhao/GANet-master/libs/sync_bn/build/lib/sync_bn_gpu.cpython-36m-x86_64-linux-gnu.so)
frame #3: <unknown function> + 0x1be75 (0x7f8699280e75 in /home/lvhao/GANet-master/libs/sync_bn/build/lib/sync_bn_gpu.cpython-36m-x86_64-linux-gnu.so)
frame #4: <unknown function> + 0x202ae (0x7f86992852ae in /home/lvhao/GANet-master/libs/sync_bn/build/lib/sync_bn_gpu.cpython-36m-x86_64-linux-gnu.so)
frame #5: /usr/bin/python3.6m() [0x50746c]
frame #6: _PyEval_EvalFrameDefault + 0x4dd (0x507edd in /usr/bin/python3.6m)
frame #7: /usr/bin/python3.6m() [0x504e80]
frame #8: /usr/bin/python3.6m() [0x5b95e9]
frame #9: PyObject_Call + 0x3e (0x59fcee in /usr/bin/python3.6m)
frame #10: THPFunction_apply(_object*, _object*) + 0x6b1 (0x7f86e5041481 in /usr/local/lib/python3.6/dist-packages/torch/lib/libtorch_python.so)
frame #11: /usr/bin/python3.6m() [0x507217]
frame #12: _PyEval_EvalFrameDefault + 0x4dd (0x507edd in /usr/bin/python3.6m)
frame #13: /usr/bin/python3.6m() [0x5b94e5]
frame #14: PyObject_Call + 0x3e (0x59fcee in /usr/bin/python3.6m)
frame #15: _PyEval_EvalFrameDefault + 0x1ab3 (0x5094b3 in /usr/bin/python3.6m)
frame #16: /usr/bin/python3.6m() [0x504e80]
frame #17: /usr/bin/python3.6m() [0x5b96f0]
frame #18: /usr/bin/python3.6m() [0x58cabe]
frame #19: _PyObject_FastCallKeywords + 0x19c (0x5a078c in /usr/bin/python3.6m)
frame #20: /usr/bin/python3.6m() [0x5073f0]
frame #21: _PyEval_EvalFrameDefault + 0x4dd (0x507edd in /usr/bin/python3.6m)
frame #22: /usr/bin/python3.6m() [0x5b94e5]
frame #23: PyObject_Call + 0x3e (0x59fcee in /usr/bin/python3.6m)
frame #24: _PyEval_EvalFrameDefault + 0x1ab3 (0x5094b3 in /usr/bin/python3.6m)
frame #25: /usr/bin/python3.6m() [0x504e80]
frame #26: /usr/bin/python3.6m() [0x5b96f0]
frame #27: /usr/bin/python3.6m() [0x58cabe]
frame #28: _PyObject_FastCallKeywords + 0x19c (0x5a078c in /usr/bin/python3.6m)
frame #29: /usr/bin/python3.6m() [0x5073f0]
frame #30: _PyEval_EvalFrameDefault + 0x4dd (0x507edd in /usr/bin/python3.6m)
frame #31: /usr/bin/python3.6m() [0x5b94e5]
frame #32: PyObject_Call + 0x3e (0x59fcee in /usr/bin/python3.6m)
frame #33: _PyEval_EvalFrameDefault + 0x1ab3 (0x5094b3 in /usr/bin/python3.6m)
frame #34: /usr/bin/python3.6m() [0x504e80]
frame #35: /usr/bin/python3.6m() [0x5b96f0]
frame #36: /usr/bin/python3.6m() [0x58cabe]
frame #37: _PyObject_FastCallKeywords + 0x19c (0x5a078c in /usr/bin/python3.6m)
frame #38: /usr/bin/python3.6m() [0x5073f0]
frame #39: _PyEval_EvalFrameDefault + 0x4dd (0x507edd in /usr/bin/python3.6m)
frame #40: /usr/bin/python3.6m() [0x5b94e5]
frame #41: PyObject_Call + 0x3e (0x59fcee in /usr/bin/python3.6m)
frame #42: _PyEval_EvalFrameDefault + 0x1ab3 (0x5094b3 in /usr/bin/python3.6m)
frame #43: /usr/bin/python3.6m() [0x504e80]
frame #44: /usr/bin/python3.6m() [0x5b9928]
frame #45: /usr/bin/python3.6m() [0x58cabe]
frame #46: PyObject_Call + 0x3e (0x59fcee in /usr/bin/python3.6m)
frame #47: _PyEval_EvalFrameDefault + 0x1ab3 (0x5094b3 in /usr/bin/python3.6m)
frame #48: /usr/bin/python3.6m() [0x504e80]
frame #49: /usr/bin/python3.6m() [0x5b9928]
frame #50: PyObject_Call + 0x3e (0x59fcee in /usr/bin/python3.6m)
frame #51: _PyEval_EvalFrameDefault + 0x1ab3 (0x5094b3 in /usr/bin/python3.6m)
frame #52: /usr/bin/python3.6m() [0x504e80]
frame #53: /usr/bin/python3.6m() [0x5b96f0]
frame #54: /usr/bin/python3.6m() [0x58cabe]
frame #55: _PyObject_FastCallKeywords + 0x19c (0x5a078c in /usr/bin/python3.6m)
frame #56: /usr/bin/python3.6m() [0x5073f0]
frame #57: _PyEval_EvalFrameDefault + 0x4dd (0x507edd in /usr/bin/python3.6m)
frame #58: /usr/bin/python3.6m() [0x5064e4]
frame #59: /usr/bin/python3.6m() [0x507330]
frame #60: _PyEval_EvalFrameDefault + 0x4dd (0x507edd in /usr/bin/python3.6m)
frame #61: /usr/bin/python3.6m() [0x504e80]
frame #62: /usr/bin/python3.6m() [0x5c6213]
frame #63: /usr/bin/python3.6m() [0x507217]

Backend TkAgg is interactive backend. Turning interactive mode on.


the pytorch is 1.1 ubuntu16.04 and python3.6 cuda10.1 and cudnn is 7

**Comment by waychin-weiqin** [comment]
Maybe try installing CUDA10.0? I know there are some issues with PyTorch with CUDA10.1.

**Comment by cuizelu** [comment]
I want to know the "compile.sh" how to do .when  do "sh compile.sh",the error: command '/usr/local/cuda-10.0**/bin/bin/nvcc**' failed with exit status 1. I "vim ~/.bashrc" and find the $PATH is :

export CUDA_HOME=/usr/local/cuda-10.0**/bin**
export LD_LIBRARTY_PATH=/usr/local/cuda-10.0/lib64
export PATH="$PATH:$LD_LIBRARY_PATH:$CUDA_HOME"

I change the first to the "export CUDA_HOME=/usr/local/cuda-10.0" (not hava "/bin")and the error is solved. But I have the another error:"nvcc -V"  :程序“nvcc”尚未安装。 您可以使用以下命令安装：
sudo apt install nvidia-cuda-toolkit. I think if I change the $PATH (not have bin),there have the second problem,but change the $PATH (hava bin),there have the first problem

> It should be an issue of your environment $PATH.
> you should be able to check by “echo $PATH”.
> In “compile.sh” there is example to set temporary PATH , CUDA_HOME and LD_LIBRARY_PATH.

**Comment by USTC-Keyanjie** [comment]
I have encounted the same problem and I don't know how to solve it. Did you solve this?

**Comment by USTC-Keyanjie** [comment]
I have encounted the same problem and I don't know how to solve it. Did you solve this? @Lvhhhh
