### ISSUE TITLE
Compile Error.

### ISSUE THREAD

**Issue by YvanYin** [feihuzhang/GANet#80]
Hi Feihu,

When I try to compile, I face some errors. Can you help me to fix that?
I am trying to compile on our uni cluster. I have changed all path in the `compile.sh`

> module load CUDA/9.2.148.1
module load GCC/5.4.0-2.26 export LD_LIBRARY_PATH="/home/a1730322/.local/easybuild/software/Anaconda3/5.1.0/lib:$LD_LIBRARY_PATH"
export LD_INCLUDE_PATH="/home/a1730322/.local/easybuild/software/Anaconda3/5.1.0/include:$LD_INCLUDE_PATH"
export   CUDA_HOME="/apps/software/CUDA/9.0.176"
export PATH="/apps/software/CUDA/9.0.176/bin:/home/a1730322/.local/easybuild/software/Anaconda3/5.1.0/bin:$PATH"
export CPATH="/apps/software/CUDA/9.0.176/include"
export CUDNN_INCLUDE_DIR="/apps/software/CUDA/9.0.176/include"
export CUDNN_LIB_DIR="/apps/software/CUDA/9.0.176/lib64"

I use the pytorch=1.1.0, CUDA=9.2, GCC=5.4

However, I faced the following errors.

`running clean
removing 'build/temp.linux-x86_64-3.6' (and everything under it)
removing 'build'
running build
running build_ext
building 'GANet' extension
creating build
creating build/temp.linux-x86_64-3.6
creating build/temp.linux-x86_64-3.6/src
gcc -pthread -B /home/a1730322/.local/easybuild/software/Anaconda3/5.1.0/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/a1730322/.local/easybuild/software/Anaconda3/5.1.0/lib/python3.6/site-packages/torch/lib/include -I/home/a1730322/.local/easybuild/software/Anaconda3/5.1.0/lib/python3.6/site-packages/torch/lib/include/TH -I/home/a1730322/.local/easybuild/software/Anaconda3/5.1.0/lib/python3.6/site-packages/torch/lib/include/THC -I/apps/software/CUDA/9.0.176/include -I/home/a1730322/.local/easybuild/software/Anaconda3/5.1.0/include/python3.6m -c src/GANet_cuda.cpp -o build/temp.linux-x86_64-3.6/src/GANet_cuda.o -DTORCH_EXTENSION_NAME=GANet -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++11
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
src/GANet_cuda.cpp:2:29: fatal error: torch/extension.h: No such file or directory
 #include <torch/extension.h>`

**Comment by YvanYin** [comment]
I have fixed this problem.

**Comment by czy341181** [comment]
@YvanYin ,I met the same question, how do you solve this?thank you !!!

**Comment by YvanYin** [comment]
@czy341181 
Hi, my problem is caused by the path settings. 
You should correctly set all paths in compile.sh.
I use the conda to manage my environment. My environment is pytorch-110. My compile.sh is：

export LD_LIBRARY_PATH="/home/a1730322/.local/easybuild/software/Anaconda3/5.1.0/envs/pytorch-110/lib:$LD_LIBRARY_PATH"
export LD_INCLUDE_PATH="/home/a1730322/.local/easybuild/software/Anaconda3/5.1.0/envs/pytorch-110/include:$LD_INCLUDE_PATH"
export CUDA_HOME="/apps/software/CUDA/9.2.148.1"
export PATH="/home/a1730322/.local/easybuild/software/Anaconda3/5.1.0/envs/pytorch-110/bin:/apps/software/CUDA/9.2.148.1/bin:$PATH"
export CPATH="/apps/software/CUDA/9.2.148.1/include"
export CUDNN_INCLUDE_DIR="/apps/software/CUDA/9.2.148.1/include"
export CUDNN_LIB_DIR="/apps/software/CUDA/9.2.148.1/lib64"
