### ISSUE TITLE
Error during "sh compile.sh": cp: cannot stat 'build/lib*': No such file or directory

### ISSUE THREAD

**Issue by SherifShawkat** [feihuzhang/GANet#82]
Hello all, first thank you for your efforts. Secondly, I faced an error when trying to setup the code during the 1st step "sh compile.sh"

The error:
cp: cannot stat 'build/lib*': No such file or directory

I opened the "compile.sh" file and found the command "cp -r build/lib* build/lib" but there is no build folder in the main folder.

Thank you for your time.

**Comment by Wyx9352** [comment]
I also encountered this problem, how did you solve it?
