### ISSUE TITLE
compiling in win10

### ISSUE THREAD

**Issue by amaanda** [feihuzhang/GANet#9]
I am trying to compile your code on a Windows 10 machine, CUDA 10.0, Pytorch 1.1.0 and Python 3.6.8. When I run `python3 setup.py build` I get the following message:

```
1 error detected in the compilation of "C:/Users/Pichau/AppData/Local/Temp/tmpxft_00002b80_00000000-10_GANet_kernel.cpp1.ii".
error: command 'C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v10.0\\bin\\nvcc.exe' failed with exit status 1
```
any suggestion on what might be causing this?

**Comment by feihuzhang** [comment]
Currently, the code haven’t been tested on windows. But it should works if you can build pytorch from source on windows.
